### ISSUE TITLE
Remaining charging time wrong

### ISSUE THREAD

**Issue by Kolbi** [Cyr-ius/hass-audiconnect#10]
My sensor: sensor.audi_a6_avant_tfsi_e_remaining_charging_time displays in HA: 00:29 (min?) and in the app I have 2h 27min.

In debug:
          "remaining_charging_time": {
            **"value": "00:29",**
            "unit": null,
            "device_class": null,
            "icon": "mdi:battery-charging",
            "sensor_type": "sensor",
            "turn_mode": null

                 "remainingChargingTime": {
                    **"content": 145,**
                    "timestamp": "2023-03-20T09:21:20+00:00"
                  },

145 would fit to the 2:25.

Maybe issue in line: https://github.com/Cyr-ius/hass-audiconnect/blob/ab80fa74d1260044af7d5891dc36ae0a8fae21a2/custom_components/audiconnect/audiconnectpy/util.py#L374

Also the charging power switch seems not to work.

**Comment by Kolbi** [comment]
Edit I think the issue is located here: https://github.com/Cyr-ius/hass-audiconnect/blob/ab80fa74d1260044af7d5891dc36ae0a8fae21a2/custom_components/audiconnect/audiconnectpy/models.py#L398

**Comment by Kolbi** [comment]
I think it's fixed with my PR: https://github.com/Cyr-ius/hass-audiconnect/pull/11

**Comment by Kolbi** [comment]
Only the not working charging power switch is left :)

**Comment by Cyr-ius** [comment]
Please test beta version 1.0.7

**Comment by Kolbi** [comment]
Thanks will try the switch later on.

Remaining charging time will work, already tested it.

**Comment by Kolbi** [comment]
Switch seems not to work...
