### ISSUE TITLE
Login to Audi service failed: Cannot serialize non-str key None

### ISSUE THREAD

**Issue by simonepittis** [cyr-ius/hass-audiconnect#12]
This error originated from a custom integration.

Logger: custom_components.audiconnect.audiconnectpy.auth
Source: custom_components/audiconnect/audiconnectpy/auth.py:200
Integration: Audi Connect (documentation, issues)
First occurred: 20:43:55 (2 occurrences)
Last logged: 20:46:42

Login to Audi service failed: Cannot serialize non-str key None

Note: User and Pass works. tested on MyAudi website

**Comment by Cyr-ius** [comment]
Please try change password
