### ISSUE TITLE
Location not up to date

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#17]
Sometimes when I get home, the location still shows a location from a while back. I think the previous parked location. Waiting doen't resolve the issue. When I reload the integration, the position imediatly is correct. All other sensors seem correct, just the location isn't up to date. What can I provide you to look in to this issue?

**Comment by tieskuh** [comment]
For your info: the issue above is in version 1.0.7. 
Because of some issues with 1.3.0 I'm still running 1.0.7. As soon as the climatisation in 1.3.0 works (https://github.com/cyr-ius/hass-audiconnect/issues/22) I will upgrade and retest the issue above in version 1.3.0.

**Comment by oleg-d** [comment]
@tieskuh how do you install an older version such as 1.0.7?

**Comment by tieskuh** [comment]
> @tieskuh how do you install an older version such as 1.0.7?

Ik you are using HACS it is quite easy. Just redownload the integration and select the version you want to use.

![image](https://github.com/cyr-ius/hass-audiconnect/assets/115901851/3351f8e0-bee4-4134-b671-d0e9d65222f0)

![image](https://github.com/cyr-ius/hass-audiconnect/assets/115901851/8a68c737-3b1f-4352-bfe5-67b92090842e)
