### ISSUE TITLE
Is there a way to change the refresh interval?

### ISSUE THREAD

**Issue by oleg-d** [cyr-ius/hass-audiconnect#25]
How can I configure the refresh interval to be something other than 10 mins?

**Comment by oleg-d** [comment]
I am for now going to use a workaround of using [Spook ](https://github.com/frenck/spook) and automation to enable and then disable polling on an hourly basis to meet my requirements.

**Comment by coreywillwhat** [comment]
I'm on the [arjenvrh](https://github.com/arjenvrh/audi_connect_ha) fork still. Was running into the quota limit like you're describing. My phone app was locking me out as well because of all the refreshes. The arjenvrh fork lets you set the interval on install. I haven't tried this fork. Does it not prompt you on integration install?

I'm curious what the limit is. I'm happy to keep testing until i find out. Currently i reinstalled and set the refresh interval to 30mins. Will see if that gives me the same issue in the coming days.

**Comment by MatthewC105** [comment]
I edited the file: **coordinator.py**, line 19.
From: **SCAN_INTERVAL = 5**
To: **SCAN_INTERVAL = 45**

This then updates every 45 mins, which seems to have not hit the API limit so far.

**Comment by coreywillwhat** [comment]
30 mins seems okay, going to try 15m

**Comment by tieskuh** [comment]
I noticed it changed to 30 mins in version 1.3.1
I liked it better at a lower interval. Maybe it would be a good idea to make it configurable.

**Comment by bavala3010** [comment]
> 30 mins seems okay, going to try 15m

Does it continue to work with a 15 minute interval ?

**Comment by MatthewC105** [comment]
> > 30 mins seems okay, going to try 15m
> 
> Does it continue to work with a 15 minute interval ?

I tried a 20 minute interval and ran into the limit on the odd occasion (I imagine when HA has been restarted after updates, whilst also using the Audi Mobile app etc leads to more requests), so i assume this must be close to the limit. I have changed to 25 minute intervals and not had any issues for the last few weeks.

**Comment by tieskuh** [comment]
Strange. Mine works fine with a 5 minute interval...

**Comment by coreywillwhat** [comment]
I've been on 15m for a few weeks. Haven't had any issues. I rarely use the official Audi app. I use HA to automate car starts from my calendar events and trigger car starts with google assistant or scripts.

US Region -- I still use arjenvrh branch since the US still isn't working on this one.

**Comment by MatthewC105** [comment]
Perhaps it could be a regional issue, I'm ‘Rest of World’ / UK

**Comment by tieskuh** [comment]
> Perhaps it could be a regional issue, I'm ‘Rest of World’ / UK

Yes, I think so. I am in EU.

**Comment by bavala3010** [comment]
I expect that the requests from the Audi app also count, so I disabled it (logged out) and only use HA.

**Comment by tieskuh** [comment]
It would be great to be able to change the refresh interval via a configuration option in a future version.
