### ISSUE TITLE
Only 2 Entities

### ISSUE THREAD

**Issue by dempanator** [cyr-ius/hass-audiconnect#26]
Have just added my new Audi Q4 E-tron to Home Assistant using Audi connect but I can only see two entities - Door Lock & Model. How do I see all the other entities?

**Comment by hnktnk** [comment]
I'm writing here to say I have the same issue and want to monitor this.
Audi Q4 45 e-tron 2024 model.

**Comment by moritzwiechers** [comment]
Hey,
I created a [fork](https://github.com/moritzwiechers/audi_connect_ha_q4) with some adjustments to get some data for my q4 etron. 
I don't know python or home-assistant integrations. I don't know why the "old" endpoint won't work, but I found one that works in some way (different data structure) and put it in my fork. For me (located in germany) it is working and I added battery soc, milage and range. 
You can add it via a custom repository.
Maybe some skilled python dev could use the informations to enhance it.

**Comment by acdcnow** [comment]
Hey great work,
I could get as well the same data. That is a good starting point. We should be able to get the binary_sensors for doors, windows as well as the charging time and speed as well as gps locations.
Hope that somebody can help here further

**Comment by hnktnk** [comment]
Works for me. Great job!
