### ISSUE TITLE
Cant configure - invalid credentials

### ISSUE THREAD

**Issue by jaygrovr** [cyr-ius/hass-audiconnect#27]
Ok so running latest home assistant, just installed the files by copying them over to custom components, and the dialog box to setup the service always fails.  I am able to login to myaudi using my credentials but this integration is not working and not allowing me to get it setup.  Also,  is the s-pin required or not?

**Comment by tieskuh** [comment]
The Audi API had quite some downtime lately. I had the same issue. Check if the Audi app works before trying to setup the integration. S-PIN is not required as far as I know but some features will not work without it.
