### ISSUE TITLE
climatisation_target_temp is shown as distance

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#30]
See proposed patch below:

https://github.com/cyr-ius/hass-audiconnect/compare/master...tieskuh:hass-audiconnect:patch-1

Also 2730 will give a the exact temperature. In number.py 2731 will give a temperature that is off a bit.

https://github.com/cyr-ius/hass-audiconnect/compare/master...tieskuh:hass-audiconnect:patch-2

**Comment by oleg-d** [comment]
I read somewhere that this value is decakelvin
