### ISSUE TITLE
Sensor charging_state

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#31]
charging_state is a switch in v1.3.0. Before it was a sensor. 
It would be great if it could be added as a sensor because it can have more values which now aren't visible.

https://github.com/cyr-ius/hass-audiconnect/compare/master...tieskuh:hass-audiconnect:patch-4

**Comment by cyr-ius** [comment]
Add to 1.3.3

**Comment by tieskuh** [comment]
Thank you. I'll close this issue!
