### ISSUE TITLE
Feature request: Is there any chance to get the short-term memory trip data from the app

### ISSUE THREAD

**Issue by wigster** [cyr-ius/hass-audiconnect#40]
Is this trip data which the myaudi app can show available from the API? It would be great to be able to store and analyse energy efficiency of the car over time through HA.

**Comment by cyr-ius** [comment]
It's possible, can you submit the diagnostic file and I can tell you if I can develop the functionality.
"Download diagnostics."

![image](https://github.com/cyr-ius/hass-audiconnect/assets/1258123/9de63cc9-7519-40b6-b204-3cd989143518)

**Comment by wigster** [comment]
It seems that the data are there in the data dump:

[config_entry-audiconnect-bd1091946121f7ada2f327afe3ead1a1.json.txt](https://github.com/cyr-ius/hass-audiconnect/files/13808204/config_entry-audiconnect-bd1091946121f7ada2f327afe3ead1a1.json.txt)

```json
          "trip_short_current": {
            "tripID": 2681925338,
            "averageElectricEngineConsumption": 22.7,
            "averageFuelConsumption": 0.5,
            "averageSpeed": 36,
            "mileage": 37,
            "startMileage": 42614,
            "traveltime": 62,
            "timestamp": "2023-12-31T16:28:20+00:00",
            "overallMileage": 42651
          },
          "trip_short_reset": {
            "tripID": 2681846957,
            "averageElectricEngineConsumption": 1.3,
            "averageFuelConsumption": 8.2,
            "averageSpeed": 81,
            "mileage": 208,
            "startMileage": 42405,
            "traveltime": 154,
            "timestamp": "2023-12-31T11:55:48+00:00",
            "overallMileage": 42614
          },
          "trip_long_current": {
            "tripID": 2676313841,
            "averageElectricEngineConsumption": 9.4,
            "averageFuelConsumption": 8.1,
            "averageSpeed": 40,
            "mileage": 30436,
            "startMileage": 12215,
            "traveltime": 53627,
            "timestamp": "2023-12-31T16:28:20+00:00",
            "overallMileage": 42651
          }
```
It would be great to get at the trip_short_current key, which basically contains the stats for the last journey. The timestamp is the time of parking the car. The trip_short_reset key seems to be the previous trip. trip_long_current is a separate counter which I haven't figured out yet how to reset.

If I may suggest, it would seem to me idea to get the data as attributes in some sensor that contained the tripID or maybe the timestamp. It would then be easy to trigger off its state some template sensors that would count the total fuel consumed or some other statistics.

**Comment by wigster** [comment]
In a really rather embarassing moment, I've just realised that this information is already in the long-term and short-term sensor attributes, just as I was suggesting would be good to have. I shall close with many thanks!
