### ISSUE TITLE
Personal Data Exposed in Diagnostics File

### ISSUE THREAD

**Issue by coreywillwhat** [cyr-ius/hass-audiconnect#43]
**Describe the bug**
The diagnostics file exposes Personal Data. Some values are redacted, but the following values are not redacted: 

"personal_data" > addresses:
- name (Ln 5133)
- zipCode (Ln 5134)
- street (Ln 5136)
- state (Ln 5137)

"personal_data" > phoneNumbers:
- number (Ln 5153)

VIN is exposed in the following locations:
- vehicle_details (Ln 353)
- data > entry > options (Ln 180)

**Diagnostics file**
I've attached the diagnostics file and replaced all unredacted data with "XXXXXXXXXXXXX"
[config_entry-audiconnect-7db4164f602f02a40125130d87a0bff0.json.txt](https://github.com/cyr-ius/hass-audiconnect/files/13795707/config_entry-audiconnect-7db4164f602f02a40125130d87a0bff0.json.txt)

**Expected behavior**
All Personal Data should be redacted from diagnostics file.

**Comment by cyr-ius** [comment]
Fix  in 1.4.2 version.
I delete the personal data section, not used for diagnosis

The VIN number is not confidential data. It is displayed on the windshield of vehicles and without the device pairing code you cannot do anything

Thank you for this feedback

**Comment by coreywillwhat** [comment]
I saw VIN was redacted in a few places and not others, so just wanted to be sure you were aware. Thanks for all your work on this.
