### ISSUE TITLE
Provide functionality of service actions in documentation

### ISSUE THREAD

**Issue by coreywillwhat** [cyr-ius/hass-audiconnect#50]
**The current list of service actions includes:**
- Lock: Door Locks
- Climater: Cabin Heating/Cooling
- Charger: Turn On/Off Charging
- Pre Heating: Unknown functionality
- Windows Heating: Glass Surface Heating
- Ventilation: Unknown functionality (possibly seat heater/ventilation)

**Current Input Select Options:**
- Climatisation Target Temp: Target Temperature for Cabin Heating/Cooling
- Climatisation Heater Src: Unknown functionality

**Request:**
- Provide a clear description of the service actions "Pre Heating" and "Ventilation". Provide description of "Heater Src".

**Additional Information:**
- This information is crucial for effectively debugging and determining available features for various vehicles.

**Comment by tieskuh** [comment]
I guess this should probably be moved to the discussion board so everyone can share their experience specific to their car model. 
These are API-functions that will depend on the car you have.

**Comment by coreywillwhat** [comment]
Yeah could be better over there, was just thinking if it was added to the readme/documentation it might be useful for everyone to determine what to use for certain scenarios.

**Comment by tieskuh** [comment]
> Yeah could be better over there, was just thinking if it was added to the readme/documentation it might be useful for everyone to determine what to use for certain scenarios.

But to document that, you first have to find out what specific car models support and how they act to a certain command. I'm guessing cyr-ius only has his own car to test on. His documentation would be for that car alone and wouldn't make much sense. Most cars only support some of all available functions.

**Comment by coreywillwhat** [comment]
That's fair. I'll close this and move my questions to discussion, but i'm curious if you know what the ventilation and pre-heater functions mean? I only took guesses in the first post.

Since you have an e-tron i'd guess you have the same if not more options than i would have on my q5 PHEV. I'd guess the preheater is something to do with warming the electric motors and ventilation all i could think would be seat ventilation/heater.
