### ISSUE TITLE
No Vehicles found - 502 error

### ISSUE THREAD

**Issue by planetmarshall** [cyr-ius/hass-audiconnect#57]
**Describe the bug**

The UI reports that the integration is successfully configured, but no entities are added and no vehicles appear in the dropdown,

In the debug log, there are repeated errors along the lines of:

```
2024-01-06 10:59:57.960 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE: {"error":{"errorCode":"VSR.security.9007","description":"The referenced vehicle with VIN: <redacted> could not be found or has no association to the given User"}} ,return_code '502'
```

The redacted VIN matches my vehicle, so it has managed to retrieve it from my account successfully.

I have an Audi Q4

**Comment by tieskuh** [comment]
And your car shows up in the app correctly without warnings? I know your dealer has to authorize your car in the app for you once. For a new car that usually happens on purchase but for a second hand car you will probably have to visit the dealer.

**Comment by Kolbi** [comment]
Try to downgrade to: https://github.com/cyr-ius/hass-audiconnect/tree/1.4.8
