### ISSUE TITLE
Cannot change climate temperature

### ISSUE THREAD

**Issue by Zuendapp** [cyr-ius/hass-audiconnect#58]
Hi :),

I'm not able to change the climate temperature.
But I have to say, I don't have the ability to change the temperature in the Audi App too, because I think it's not possible with a hybird A3 TFSIe (MY2022).
I've seen a Seat Formentor Hybrid and there it is possible to change the temperature in the Seat App.
Do you see any chance to get this working with an Audi?

Thank you!

BR

**Comment by cyr-ius** [comment]
If missing in the application, it is normal that you will not be able to do it with HA

**Comment by Zuendapp** [comment]
Ok thank you!!

BR
