### ISSUE TITLE
Question: How to change api version

### ISSUE THREAD

**Issue by DutchKillerbee** [cyr-ius/hass-audiconnect#59]
**Describe the bug**
I am unable to find the location where to change the charger api version.
I can't find the option in the configuration screen.

This is the only option I have when I hit the configure button.
![image](https://github.com/cyr-ius/hass-audiconnect/assets/3790491/2ca5d526-f20a-456c-aecc-921845a89714)

I have a Q3 tfsi-e and start stop charging doens't work
Start stop climatisation works so I would like to try a different api version for the charger.

(Start stop charger worked in the arjenvrh version)

Thanks for your help

**Comment by DutchKillerbee** [comment]
Found it :)
![image](https://github.com/cyr-ius/hass-audiconnect/assets/3790491/88461cec-ec7b-49fd-8e5a-6dda558f22d8)

**Comment by DutchKillerbee** [comment]
FYI Audi Q3 TFSi-e start stop charging works with api V3

**Comment by Kolbi** [comment]
Can you add it please here: https://github.com/cyr-ius/hass-audiconnect/discussions/48 ?
