### ISSUE TITLE
Cannot Connect to API

### ISSUE THREAD

**Issue by Seidlm** [cyr-ius/hass-audiconnect#60]
Hi, after entering my credentials i get the error

<img width="415" alt="image" src="https://github.com/cyr-ius/hass-audiconnect/assets/25500393/e09546df-d958-4bca-905e-cb49a5ac66cf">

i have access to Audi connect App and it worked with other HA integrations.

**Comment by sahnebar** [comment]
Hi, 

i got the same error, is there any fix out there? 

Kind Regards, 
Sani

**Comment by mm98** [comment]
I also started seeing this. Can't reinstall the integration.

**Comment by possm** [comment]
Could very well be related to https://github.com/cyr-ius/hass-audiconnect/issues/64

**Comment by Hoekeren** [comment]
I have the same issue.
Denne fejl stammer fra en brugerdefineret integration.

Logger: audiconnectpy.auth
Kilde: custom_components/audiconnect/config_flow.py:76
integration: Audi Connect (dokumentation, problemer)
Første forekomst: 08.12.17 (3 forekomster)
Senest logget: 08.12.39

Login to Audi service failed, trying again in 10 seconds [ERROR:Error occurred while communicating with Audi Connect.]
Login to Audi service failed: Error occurred while communicating with Audi Connect.

**Comment by cyr-ius** [comment]
Fix with latest version
