### ISSUE TITLE
Integration stopped working - Audi API changed

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#64]
**Describe the bug**
The location sensor became unavailable overnight. 
<img src="https://github.com/cyr-ius/hass-audiconnect/assets/115901851/c7457b3a-2ee3-4fbc-bc64-ba2c5fb8c0ec" width=400 />

At the same time a home assistant operating system update installed. So it might be because of that update or because of the reboot after the update.
<img src="https://github.com/cyr-ius/hass-audiconnect/assets/115901851/726301bd-385a-41c1-a699-b490e4e69a2d" width=400 />

A reboot of HA or reloading the integration doesn't solve the problem. The location of the car is shown in the Audi Connect app.

**Diagnostics file**
Please add the diagnostics file. This action runs all Audi APIs and stores them in raw format. Sensitive data is hidden
[config_entry-audiconnect-a822b94995e84ebc08e4f7f866511bea.json](https://github.com/cyr-ius/hass-audiconnect/files/14417395/config_entry-audiconnect-a822b94995e84ebc08e4f7f866511bea.json)

**Additional context**
Anyone else experienced the same problem after updating to the latest HAOS version?

**Comment by guidokieboom** [comment]
I experienced exactly the same. Right after HA update yesterday. Today location still unavailable. On 27 Feb 2024, at 10:36, tieskuh ***@***.***> wrote:﻿
Describe the bug
The location sensor became unavailable overnight.
image.png (view on web)
At the same time a home assistant operating system update installed. So it might be because of that update or because of the reboot after the update.
image.png (view on web)
A reboot of HA or reloading the integration doesn't solve the problem. The location of the car is shown in the Audi Connect app.
Diagnostics file
Please add the diagnostics file. This action runs all Audi APIs and stores them in raw format. Sensitive data is hidden
config_entry-audiconnect-a822b94995e84ebc08e4f7f866511bea.json
Additional context
Anyone else experienced the same problem after updating to the latest HAOS version?

**Comment by tieskuh** [comment]
For me, everything but the location works (for now).

**Comment by tieskuh** [comment]
Arjenvrh's integration seems to be affected too: https://github.com/arjenvrh/audi_connect_ha/issues/228

**Comment by oleg-d** [comment]
All my sensors are unavailable :( I suspect it could be Audi have changed something on their side of the API, maybe.

I don't think its related to HA update as I am sure it was showing "unavailable" on my dashboard when I came home today, before doing the HA update.

**Comment by tieskuh** [comment]
> All my sensors are unavailable :( I suspect it could be Audi have changed something on their side of the API, maybe.
> 
> I don't think its related to HA update as I am sure it was showing "unavailable" on my dashboard when I came home today, before doing the HA update.

Could be. I know
- My HA updated last night
- After the reboot the location sensor became unavailable
- This morning the preheat command worked (if I remember correctly)
- Later this day all other sensors became unavailable

**Comment by titis14** [comment]
Hi, same for me. I confirm that this is not due to the update. I also did it last night and my kilometers this morning and this afternoon worked. On the other hand, the kilometers this evening have not increased.

**Comment by tieskuh** [comment]
> Hi, same for me. I confirm that this is not due to the update. I also did it last night and my kilometers this morning and this afternoon worked. On the other hand, the kilometers this evening have not increased.

For me it also kept working after the update (except for the location). But it stopped working later. You also did the update so I think we cannot rule out it is because of the update. If I have time I will try to roll back to be sure. If someone else already tried rolling back to the previous HA please let me know.

**Comment by tieskuh** [comment]
If I look at the debug log, I can see my car data in the logs. So the API definatly works. 
The log ends with:
`2024-02-27 22:20:37.395 DEBUG (MainThread) [custom_components.audiconnect.coordinator] Finished fetching audiconnect data in 3.615 seconds (success: True)`

**Comment by possm** [comment]
> > 
> 
> For me it also kept working after the update (except for the location). But it stopped working later. You also did the update so I think we cannot rule out it is because of the update. If I have time I will try to roll back to be sure. If someone else already tried rolling back to the previous HA please let me know.

Downgraded to HA 2024.2.1, then did a rollback from a backup to 2024.2.3. No changes. All entities still unavailable,

**Comment by wigster** [comment]
For me things were fine, I upgraded 2024.2.3 -> 2024.2.4 just now and the entities generated by Audi connect are all unavailable.

**Comment by Kolbi** [comment]
@cyr-ius have a look into here: https://github.com/arjenvrh/audi_connect_ha/issues/228#issuecomment-1968278450

This fork seesm to use the new API: https://github.com/moritzwiechers/audi_connect_ha_q4 as mentioned https://github.com/arjenvrh/audi_connect_ha/issues/228#issuecomment-1968294241

**Comment by Kolbi** [comment]
Especially this file is interesting: https://github.com/moritzwiechers/audi_connect_ha_q4/blob/master/custom_components/audiconnect/audi_services.py but I guess your source needs to be updated here https://github.com/cyr-ius/audiconnectpy

**Comment by Kolbi** [comment]
Created: https://github.com/cyr-ius/audiconnectpy/pull/19

**Comment by moritzmaier84** [comment]
> Created: [cyr-ius/audiconnectpy#19](https://github.com/cyr-ius/audiconnectpy/pull/19)

how does that work? never did it before. please help :)

**Comment by Kolbi** [comment]
Just wait currently. I provided maybe the fix - @cyr-ius has to accept the PR and then generate a new version. This version can then be download with HACS.

**Comment by DutchKillerbee** [comment]
> Created: [cyr-ius/audiconnectpy#19](https://github.com/cyr-ius/audiconnectpy/pull/19)

This only fixes the car position right?

**Comment by moritzmaier84** [comment]
> ided maybe

That sounds great, thank you! I hope it will also work for non-electric cars then.

**Comment by titis14** [comment]
> Just wait currently. I provided maybe the fix - @cyr-ius has to accept the PR and then generate a new version. This version can then be download with HACS.

Hi, I set this up last week and couldn't find it on HACS. I had to install it by hand. On HACS it is not version of cyr-ius

**Comment by Kolbi** [comment]
> > Just wait currently. I provided maybe the fix - @cyr-ius has to accept the PR and then generate a new version. This version can then be download with HACS.
> 
> Hi, I set this up last week and couldn't find it on HACS. I had to install it by hand. On HACS it is not version of cyr-ius ![firefox_2024-02-28_19-05-08](https://private-user-images.githubusercontent.com/26297241/308664755-7daf27be-bbbe-4ba3-a326-e0845e69891f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDkzNTUsIm5iZiI6MTcwOTE0OTA1NSwicGF0aCI6Ii8yNjI5NzI0MS8zMDg2NjQ3NTUtN2RhZjI3YmUtYmJiZS00YmEzLWEzMjYtZTA4NDVlNjk4OTFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE5MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGNkOGMzMmQyMWY1NzM4OTk3N2E1ZjZlMzQ3OWJmMmEzZWY1MWFmMGM2MTAwMTIxNzEwM2RjZGRhMTMyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Etj8eJbnv2cB3nPr1-IyT2p95MampK_OUJBkOks2KHI)

Add it as custom repository in HACS. :)

**Comment by GMTheDoctor** [comment]
> > > Just wait currently. I provided maybe the fix - @cyr-ius has to accept the PR and then generate a new version. This version can then be download with HACS.
> 
> > 
> 
> > Hi, I set this up last week and couldn't find it on HACS. I had to install it by hand. On HACS it is not version of cyr-ius ![firefox_2024-02-28_19-05-08](https://private-user-images.githubusercontent.com/26297241/308664755-7daf27be-bbbe-4ba3-a326-e0845e69891f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDkzNTUsIm5iZiI6MTcwOTE0OTA1NSwicGF0aCI6Ii8yNjI5NzI0MS8zMDg2NjQ3NTUtN2RhZjI3YmUtYmJiZS00YmEzLWEzMjYtZTA4NDVlNjk4OTFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE5MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGNkOGMzMmQyMWY1NzM4OTk3N2E1ZjZlMzQ3OWJmMmEzZWY1MWFmMGM2MTAwMTIxNzEwM2RjZGRhMTMyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Etj8eJbnv2cB3nPr1-IyT2p95MampK_OUJBkOks2KHI)
> 
> 
> 
> Add it as custom repository in HACS. :)

What do you mean? Where can I find the custom repository? Sorry for the basic question 🥲

**Comment by GMTheDoctor** [comment]
> > > > > Just wait currently. I provided maybe the fix - @cyr-ius has to accept the PR and then generate a new version. This version can then be download with HACS.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Hi, I set this up last week and couldn't find it on HACS. I had to install it by hand. On HACS it is not version of cyr-ius ![firefox_2024-02-28_19-05-08](https://private-user-images.githubusercontent.com/26297241/308664755-7daf27be-bbbe-4ba3-a326-e0845e69891f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDkzNTUsIm5iZiI6MTcwOTE0OTA1NSwicGF0aCI6Ii8yNjI5NzI0MS8zMDg2NjQ3NTUtN2RhZjI3YmUtYmJiZS00YmEzLWEzMjYtZTA4NDVlNjk4OTFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE5MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGNkOGMzMmQyMWY1NzM4OTk3N2E1ZjZlMzQ3OWJmMmEzZWY1MWFmMGM2MTAwMTIxNzEwM2RjZGRhMTMyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Etj8eJbnv2cB3nPr1-IyT2p95MampK_OUJBkOks2KHI)
> > > 
> > > 
> > > Add it as custom repository in HACS. :)
> > 
> > 
> > What do you mean? Where can I find the custom repository? Sorry for the basic question 🥲
> 
> You're welcome. See: https://hacs.xyz/docs/faq/custom_repositories/ use https://github.com/cyr-ius/hass-audiconnect/ as URL.

Thank you! I installed the integration but I got "Can't connect to the API"

**Comment by tieskuh** [comment]
> > > > > > Just wait currently. I provided maybe the fix - @cyr-ius has to accept the PR and then generate a new version. This version can then be download with HACS.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Hi, I set this up last week and couldn't find it on HACS. I had to install it by hand. On HACS it is not version of cyr-ius ![firefox_2024-02-28_19-05-08](https://private-user-images.githubusercontent.com/26297241/308664755-7daf27be-bbbe-4ba3-a326-e0845e69891f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDkzNTUsIm5iZiI6MTcwOTE0OTA1NSwicGF0aCI6Ii8yNjI5NzI0MS8zMDg2NjQ3NTUtN2RhZjI3YmUtYmJiZS00YmEzLWEzMjYtZTA4NDVlNjk4OTFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE5MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGNkOGMzMmQyMWY1NzM4OTk3N2E1ZjZlMzQ3OWJmMmEzZWY1MWFmMGM2MTAwMTIxNzEwM2RjZGRhMTMyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Etj8eJbnv2cB3nPr1-IyT2p95MampK_OUJBkOks2KHI)
> > > > 
> > > > 
> > > > Add it as custom repository in HACS. :)
> > > 
> > > 
> > > What do you mean? Where can I find the custom repository? Sorry for the basic question 🥲
> > 
> > 
> > You're welcome. See: https://hacs.xyz/docs/faq/custom_repositories/ use https://github.com/cyr-ius/hass-audiconnect/ as URL.
> 
> Thank you! I installed the integration but I got "Can't connect to API"

Did you see the title of the issue you are commenting in? ;-)
We have to wait until a fix is released. The integration is not working at this time.

**Comment by oleg-d** [comment]
Any updates from this? @cyr-ius

**Comment by oleg-d** [comment]
To anyone still wondering, come on over to the other integration which is now where the main effort is happening https://github.com/audiconnect/audi_connect_ha

**Comment by titis14** [comment]
Hi,
In fact I made the change and everything is OK. I'm just missing the oil level and tire condition.

**Comment by tieskuh** [comment]
Thanks @cyr-ius for fixing the integration!
