### ISSUE TITLE
debug log wanted.

### ISSUE THREAD

**Issue by Heelderpeel** [cyr-ius/hass-audiconnect#65]
Are there people who still use this integration? I am looking for a debug log of this integration.
I deleted it and now I can't install it anymore.
There are now some people working on the original GitHub of which this is a fork. I have asked to add extra sensors for, for example, the tires. and for that they need the debug log.

**Comment by tieskuh** [comment]
Does this help?
https://github.com/cyr-ius/hass-audiconnect/files/14417395/config_entry-audiconnect-a822b94995e84ebc08e4f7f866511bea.json

**Comment by Heelderpeel** [comment]
I hope so, I'll ask in the other github.
Thank you
