### ISSUE TITLE
Oil / Inspection time showing showing wrong information

### ISSUE THREAD

**Issue by superpower10** [Cyr-ius/hass-audiconnect#7]
Very strange thing.

Sensor shows days in hours when showing it in lovelace and devices -> integrations:
![2EE2E4E9-48DD-455B-B0A0-25E813B51B64](https://user-images.githubusercontent.com/20533966/222924611-f8472222-e167-48f2-91c2-06332cf96abc.jpeg)

When tapping on the sensor then on the gear it shows it days:
![8CC5951C-8282-41CA-A806-DBB8DBCD101A](https://user-images.githubusercontent.com/20533966/222924710-1ec81bbe-fcdc-4b0e-af13-5d1fa1c23559.jpeg)

Maybe a problem with the newest update of Home Assistant with introduced rounding?
![3E9999C4-ED52-4BAD-8D38-3CA57F092423](https://user-images.githubusercontent.com/20533966/222924762-a123df83-d752-4e22-9769-d041e5582e3c.jpeg)

**Comment by Cyr-ius** [comment]
I'm sorry but this is a bug in the frontend of homeassistant
https://github.com/home-assistant/frontend/issues/15103
