### ISSUE TITLE
Latest to more connection

### ISSUE THREAD

**Issue by titis14** [cyr-ius/hass-audiconnect#71]
**Describe the bug**
Hi,
I just updated and the module no longer starts. I deleted and re-connected, it's still the same.
Thank

**Diagnostics file**
Please add the diagnostics file. This action runs all Audi APIs and stores them in raw format. Sensitive data is hidden
![firefox_2024-06-08_22-07-09](https://github.com/cyr-ius/hass-audiconnect/assets/26297241/727e078e-8cb4-460e-a009-bba10f3064f9)

**Expected behavior**

**Screenshots**
![firefox_2024-06-08_22-02-33](https://github.com/cyr-ius/hass-audiconnect/assets/26297241/9a04cd69-e4ea-483d-bf47-ab7b020e0e4d)

**Comment by cyr-ius** [comment]
Please try 2.0.5 version , if continue , press "Activer l'enregistrement des journaux" and Wait somes Retry. 
Stop record and post the log.

**Comment by titis14** [comment]
Hi, with this new version it's OK
Thanks
