### ISSUE TITLE
Plug lock / plug state

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#73]
1) The plug lock seems to be inverted. The binary sensor **binary_sensor.audi_e_tron_plug_lock** has the exact opposite state. So it is locked when the plug is actually unlocked and the other way around.

2) The plug state sensor is missing. In the previous version, there was a sensor 'plug state' which showed if the car was connected to a charger. Is there a way to get it back?

**Comment by cyr-ius** [comment]
please upload the diagnostic file, this helps identify anomalies and add new sensors if necessary

**Comment by tieskuh** [comment]
I saw you added the plug state in the latest version. It seems to work! I created a pull for the incorrect device_class: https://github.com/cyr-ius/hass-audiconnect/pull/74

For the plug lock, I would like to send you a diagnostics file but when I click on download diagnostics, nothing happens.
I can download the debug log, but there is a lot of personal information in that file.

**Comment by cyr-ius** [comment]
Ok merge all et fix inverve , test 2.0.8

**Comment by cyr-ius** [comment]
For diagnostic , select device et click download diagnostic.
Download diagnostic from integration have a issue #119204

**Comment by tieskuh** [comment]
Ah, that's why the diagnostics didn't work. Thanks!

Plug lock still is showing 'vergrendeld' which means 'locked'. It should be 'unlocked'. 

![image](https://github.com/cyr-ius/hass-audiconnect/assets/115901851/d54cd3fd-dc91-481f-894c-cce463527626)

In the history you can see it showes both states. But inversed.
![image](https://github.com/cyr-ius/hass-audiconnect/assets/115901851/d5aea68f-741e-42e1-a637-e7dd08cc6725)

Diagnostics attached!
[config_entry-audiconnect-4b46c0432e37e4a752376be96c057293.json](https://github.com/user-attachments/files/15760457/config_entry-audiconnect-4b46c0432e37e4a752376be96c057293.json)

**Comment by cyr-ius** [comment]
Thank , 'im found issue. Fix to 2.0.9

**Comment by tieskuh** [comment]
Yes, it seems fixed indeed!
