### ISSUE TITLE
Location sensor is created with name 'None'

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#76]
Might be a translation missing or something. The sensor entity_id and name is 'None'. I think it should be 'Position' or something similar.

![image](https://github.com/cyr-ius/hass-audiconnect/assets/115901851/b5b5e02a-39bc-435e-8a67-91c6fcb51944)

Not really a problem, but maybe a quick fix for a future version.

**Comment by cyr-ius** [comment]
Fix to 2.1.1
