### ISSUE TITLE
Q4 Stuff missing/not working (model 2024)

### ISSUE THREAD

**Issue by pergolafabio** [cyr-ius/hass-audiconnect#86]
**Describe the bug**
Hi @cyr-ius , i got a new Q4 model 2024 this week, testing your fork, since the original fork doesnt provide all sensors, seems yours can do more
First of all, i see the doors/windows/trunk status "open" while its closed?
CLimater start/stop doesnt work, see error below

`2024-07-24 09:01:56.957 ERROR (MainThread) [custom_components.audiconnect.services] ('Service not found: %s -%s (%s)', 'https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/BE/vehicles/XXXX/climater/actions', {'error': {'errorCode': 'climatisation.auth.forbidden', 'description': 'The referenced vehicle with VIN: XXXXcould not be found or has no association to the given User'}}, 403)`

Location doesnt work, see error below:

```
2024-07-24 09:05:50.756 ERROR (MainThread) [homeassistant.components.device_tracker] Error adding entity device_tracker.audi_q4_e_tron_position for domain device_tracker with platform audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1362, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 237, in state
    if self.latitude is not None and self.longitude is not None:
       ^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/device_tracker.py", line 42, in latitude
    return self.vehicle.position.latitude
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'latitude'
```

**Additional context**
I have Frida enabled on my Laptop, so i can sniff/trace the API from the myAudi app, i think some endpoints are changed... For climate start/stop for example, i see below:

`https://emea.bff.cariad.digital/vehicle/v1/vehicles/xxx/climatisation/start`

with request

```
{
  "targetTemperature": 22,
  "targetTemperatureUnit": "celsius",
  "climatisationWithoutExternalPower": true,
  "climatizationAtUnlock": false,
  "windowHeatingEnabled": false,
  "zoneFrontLeftEnabled": false,
  "zoneFrontRightEnabled": false,
  "zoneRearLeftEnabled": false,
  "zoneRearRightEnabled": false
}
```

for stop:

`https://emea.bff.cariad.digital/vehicle/v1/vehicles/xxx/climatisation/stop`

For response:

https://emea.bff.cariad.digital/vehicle/v1/vehicles/XXX/pendingrequests

with response:

```
{
  "data": [
    {
      "id": "8cf8437d-94a5-49fa-9b12-60ea1bd9c2c3",
      "userId": "0e0f02f7-620c-42e5-87d3-35d76f700a75",
      "vin": "XXXX",
      "httpMethod": "POST",
      "path": "/vehicles/XXXX/climatisation/start",
      "capability": "climatisation",
      "operation": "start",
      "operationGroup": "climatisation",
      "body": "{\"callback\":\"https://emea.bff.cariad.digital/vehicle/v1/vehicles/callbacks/XXXX/climatisation/start/POST\",\"climatisationWithoutExternalPower\":true,\"targetTemperature\":21,\"targetTemperatureUnit\":\"celsius\",\"climatizationAtUnlock\":false,\"windowHeatingEnabled\":false,\"zoneFrontLeftEnabled\":false,\"zoneFrontRightEnabled\":false}",
      "vcfRequestId": "ad460379-da19-443d-bec9-58818ef275ef",
      "status": "in_progress",
      "queuedOperation": null,
      "timestamp": "2024-07-24T11:35:03.723443436Z"
    },
    {
      "id": "ab1cef0e-d047-4fba-9dc3-b3b6691a6336",
      "userId": "0e0f02f7-620c-42e5-87d3-35d76f700a75",
      "vin": "XXX",
      "httpMethod": "PUT",
      "path": "/vehicles/XXXX/climatisation/settings",
      "capability": "climatisation",
      "operation": "settings",
      "operationGroup": "climatisationSettings",
      "body": "{\"callback\":\"https://emea.bff.cariad.digital/vehicle/v1/vehicles/callbacks/XXX/climatisation/settings/PUT\",\"climatisationWithoutExternalPower\":true,\"targetTemperature\":21,\"targetTemperatureUnit\":\"celsius\",\"climatizationAtUnlock\":false,\"windowHeatingEnabled\":false,\"zoneFrontLeftEnabled\":false,\"zoneFrontRightEnabled\":false}",
      "vcfRequestId": "94f83793-6c2d-43ce-9f6f-95098b372d53",
      "status": "successful",
      "queuedOperation": null,
      "timestamp": "2024-07-24T11:30:13.249758808Z"
    }
  ]
}
```
eventually:

`     "status": "successful",`

@moritzwiechers : What is still working/nor working for you?

**Comment by pergolafabio** [comment]
The Wakeup/refresh doesnt work either, i get 404 errors ...
I can help you with the new endpoints if you want ..., just tell me what you need? WHat car do you have btw?

**Comment by pergolafabio** [comment]
For the door status, i see the Q4 entities are unsupported in the diag file, however, the overal doorlock is "locked", see below, in diag file, but the entitty itself says "unlocked"

```
        "async_get_selectivestatus": {
          "access": {
            "accessStatus": {
              "value": {
                "overallStatus": "safe",
                "carCapturedTimestamp": "0001-01-01T00:00:00Z",
                "doors": [
                  {
                    "name": "bonnet",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "trunk",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "rearRight",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "rearLeft",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "frontRight",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "frontLeft",
                    "status": [
                      "unsupported"
                    ]
                  }
                ],
                "windows": [
                  {
                    "name": "sunRoof",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "roofCover",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "sunRoofRear",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "frontLeft",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "frontRight",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "rearLeft",
                    "status": [
                      "unsupported"
                    ]
                  },
                  {
                    "name": "rearRight",
                    "status": [
                      "unsupported"
                    ]
                  }
                ],
                "doorLockStatus": "locked"
              }
            }
          },
```

![image](https://github.com/user-attachments/assets/ac8dc9d6-d9bf-459b-b24c-740559f10030)

**Comment by pergolafabio** [comment]
Also usefull, command to set the climate temp, seems different also? here is from toolkit...

URL:

https://emea.bff.cariad.digital/vehicle/v1/vehicles/XXX/climatisation/settings

Request:

```
{
  "targetTemperature": 21,
  "targetTemperatureUnit": "celsius",
  "climatisationWithoutExternalPower": true,
  "climatizationAtUnlock": false,
  "windowHeatingEnabled": false,
  "zoneFrontLeftEnabled": false,
  "zoneFrontRightEnabled": false
}
```

**Comment by jlatvala** [comment]
@pergolafabio 
Just FYI, the "original" Audi integration (https://github.com/audiconnect/audi_connect_ha )
works with my 2023 Q4. At least I can see 39 entities. 
Maybe restarting HA after logging in into Audi integration will solve your problems too?
I have newer tried any services, not sure if they work.

The only problem with that integration (and with other Audi/Audi Q4 integrations I have tested) is that it loses the connection to the Audi servers after some days (I suppose, re-authentication is needed, haven't checked though). I know when this happens because Q4 location updates don't work anymore.
Then I need to restart HA and everything works again few days. Luckily there are HA upgrades few times a month, and for me it is usually often enough to keep my Audi connection live.

**Comment by pergolafabio** [comment]
Hey, i started with that one, but i dont get 39 entities at all , jus a few
also climate/door status doesnt work, gps location is missing

What model of car do you have? i have a 2024 model, brand new, maybe stuff is changed ?
My endpoints are different if i sniff the app , i also see 404 errors when i use this or the other fork, so audi must have changed something

**Comment by pergolafabio** [comment]
is the GPS location still working for you? and climate control?  what model do you have , also 2024 ?

**Comment by cyr-ius** [comment]
ok, I'll do that for you next week

**Comment by pergolafabio** [comment]
> ok, I'll do that for you next week

Let me know if you need more info/endpoints? Maybe its only needed for 2024 models? not sure

**Comment by pergolafabio** [comment]
> @pergolafabio Just FYI, the "original" Audi integration (https://github.com/audiconnect/audi_connect_ha ) works with my 2023 Q4. At least I can see 39 entities. Maybe restarting HA after logging in into Audi integration will solve your problems too? I have newer tried any services, not sure if they work.
> 
> The only problem with that integration (and with other Audi/Audi Q4 integrations I have tested) is that it loses the connection to the Audi servers after some days (I suppose, re-authentication is needed, haven't checked though). I know when this happens because Q4 location updates don't work anymore. Then I need to restart HA and everything works again few days. Luckily there are HA upgrades few times a month, and for me it is usually often enough to keep my Audi connection live.

for info, if i use that integration, i can only see these entities...

![image](https://github.com/user-attachments/assets/18a3d5c4-df98-4afb-9c81-7ec985b9212a)

**Comment by pergolafabio** [comment]
Yeah, i also have a issue open there to provide more info about the API , probably something changed in API for 2023 vs 2024 models
What i'm missing in your sensor list , is the climate state? like "off"/ "heating" ? ... ? 
do you also have the "device" entity with GPS coordinates?

**Comment by jlatvala** [comment]
I can't find anything related to the climate, but I have this:
![image](https://github.com/user-attachments/assets/634538ce-2bed-4809-805a-9d930089c584)

My position entity has latitude and longitude as attributes.

And the location is Finland.

**Comment by pergolafabio** [comment]
Can you do a remote lock/unlock? I don't have that feature on my car...
The climate state is possible in the fork, I request to add it also on the other integration

**Comment by jlatvala** [comment]
> Can you do a remote lock/unlock?

As far as I know lock/unlock has never been possible for Q4 using myAudi app. 
I just tested unlocking via HA and didn't work:
`Unable to unlock xxx: object of type 'NoneType' has no len()`

Also start climatisation (as a service call 'Audi Connect: Execute Vehicle Action') did not work (404, ...vwg-connect.com)

**Comment by pergolafabio** [comment]
yeah, they are also fixning it now in this fork  : https://github.com/audiconnect/audi_connect_ha

they already fixed the climatisation state already, that wasnt working either

**Comment by pergolafabio** [comment]
quick update , my GPS location is now working, seems an issue with my license!

**Comment by pergolafabio** [comment]
hey @cyr-ius , you dont need to add it here, its already be worked on in the official repo
once added there, maybe you can compare the code to integrate it later, so you know the other endpoints as well for other regions.., gonna close here
